FROM elasticsearch:7.12.1
LABEL maintainer="gzp@goozp.com"

ENV discovery.type=single-node
#RUN su elasticsearch && elasticsearch-plugin install -b https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v6.7.2/elasticsearch-analysis-ik-6.7.2.zip
# new file config/analysis/synonyms.txt
#RUN mkdir config/analysis && touch config/analysis/synonyms.txt